= Wicket autoconfiguration with Spring Boot

NOTE: http://search.maven.org/#search|ga|1|com.giffing.wicket.spring.boot

This project makes it easy to create Wicket projects with a minimum
of configuration effort. It uses Spring Boot to autoconfigure Wickets core and
its extension (related projects like wicketstuff, beanvalidation...( with an reasonable default value which can be overridden over property files.

Spring Boot is using embedded servlet containers so you don't have to deploy the Application to an e.g.
Tomcat by hand.

The detailed description of the autoconfiguration support can be read in the <<extension>> section.

This project is automatically registers the needed
link:wicket-spring-boot-starter/src/main/java/com/giffing/wicket/spring/boot/starter/web/WicketWebInitializer.java[WicketFilter]
for handling Wicket requests and added the Spring applicationBean as an init parameter. 

Out of the box Wickets dependency injection support (@SpringBean) for Spring is automatically supported.
