= Wicket autoconfiguration with Spring Boot

This project (should) makes it easy to create Wicket projects with a minimum
of configuration effort. Is uses Spring Boot to autoconfigure Wickets core and
extension with an reasonable default value which can be overridden over property files.

This project detects classes in external dependencies and tries to configure
it in a reasonable way.

:toc: macro

== Getting started

To get started you have to create a new Maven (or another preferred dependency/build-management tool)
and add the *wicket-spring-boot-starter* dependency to your configuration. 

[source,xml]
----
<dependency>
	<groupId>com.giffing.wicket.spring.boot.starter</groupId>
	<artifactId>wicket-spring-boot-starter</artifactId>
	<version>${project.version}</version>
</dependency>
----

This dependency is responsibly to configure you application in a default way.  



Beside the Maven dependency configuration we need the following steps to do

. Create a class (e.g. WicketApplication) with a main method
. Annotate the class with @WicketSpringBootApplication
. Extend this class with WicketBootWebApplication
. Use the SpringApplicationBuilder to run the WicketApplication class you've created


[source,java]
----
@WicketSpringBootApplication
public class WicketApplication extends WicketBootWebApplication {
  public static void main(String[] args) throws Exception {
    new SpringApplicationBuilder()
      .sources(WicketApplication.class)
      .run(args);
  }
}
----

Thats all! When you execute the main method you will get a fully working and configured 
Wicket application with a simple login and home Page. As in every Wicket Application you can override the 
WicketBootWebApplication as usual. You can change the login/home page or the *init()* method to 
register other extensions. 

== How does it work?

To fully understand how http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-developing-auto-configuration[Spring Boots autconfiguration] and in general Spring Boot works you should read
the excellent http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/[documentation] from this fantastic http://projects.spring.io/spring-boot/[project].

As an an example we will look to the AnnotatedMountScanner configuration. The https://github.com/wicketstuff/core/tree/master/annotation[annotated mount scanner] is an project which supports
bookmarkable URLs configured by annotations on WebPage classes. If you have this '@MountPath("login")' annotation on a 
WebPage then the Page is mounted to 'http://localhost/login'.

In this project each configuration is separated in two classes to configure this particular feature/extension. The extension
consists of a property and a configuration class.

The property class holds properties to configure the specific feature. In the AnnotatedMountScannerProperties class we
found two properties:

[source,java]
----
@ConfigurationProperties(prefix = "wicket.wicketstuff.annotationscan")
public class AnnotatedMountScannerProperties {

  /**
   * @see AnnotatedMountScannerConfig
   */
  private boolean enabled = true;

  /**
   * An alternative package name for scanning for mount path if the
   * WicketApplication should not used as the root scan package
   */
  private String packagename;
}
----

This properties are imported in the BeanValidationConfig two access ... DESCRIPTION

[source,java]
----
/**
 * Enables the bean validation support if the following condition matches
 * 
 * 1. The {@link BeanValidationConfiguration} class is in the classpath. side
 * note: Bean validation required an validation implementation like hibernate
 * validator.
 * 
 * 2. The property wicket.beanvalidation.enabled has to be true (default = true)
 * 
 */
@Component
@ConditionalOnProperty(prefix = "wicket.beanvalidation", value = "enabled", matchIfMissing = true)
@ConditionalOnClass(value = org.apache.wicket.bean.validation.BeanValidationConfiguration.class)
@EnableConfigurationProperties({ BeanValidationProperties.class })
public class BeanValidationConfig implements WicketApplicationInitConfiguration {
  @Override
  public void init(WebApplication webApplication) {
    new BeanValidationConfiguration().configure(webApplication);
  }
}
----

DESCRIPTION HOW THE WicketApplicationInitConfiguration WILL BE USED

[source,java]
----
public class WicketBootWebApplication extends AuthenticatedWebApplication {
  @Autowired(required = false)
  private List<WicketApplicationInitConfiguration> configurations = new ArrayList<>();
  @Override
  protected void init() {
    super.init();
    for (WicketApplicationInitConfiguration configuration : configurations) {
      configuration.init(this);
    }
  }
}
----

=== Spring profile configuration

The Wicket Spring Boot Starter project ships with a default development configuration.
It can be activated by activating the 'development' Spring profile in the main class or over
external JVM/Maven arguments.

The default configuration can be overridden with a custom property file. See Spring Boots reference documentation http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config[here].

include::wicket-spring-boot-starter/src/main/resources/application-development.yml[]
[source,yml]
----
wicket:
  configuration-type: development
  core:
    debugsettings:
      enabled: true
  wicketstuff:
    htmlcompressor:
      enabled: false
      features:
        compressCSS: false
  devutils:
    statelesschecker:
      enabled: true
    interceptor:
      enable-live-sessions-page: true
    diskstorebrowser:
      enabled: true
  wicketsource:
    enabled: true
----




== Extensions

The following section describes the current autoconfigurations and there
required dependencies.

* <<extension-beanvalidation>>
* <<extension-core-csrf-prevention>>
* <<extension-webjars>>
* <<extension-wicketstuff-htmlcompressor>>
* <<extension-wicketstuff-annotationscan>>
* <<extension-wicketstuff-serializer-fast2>>
* <<extension-wicketstuff-serializer-kryo2>>
* <<extension-devutils-diskstorebrowser>>
* <<extension-devutils-inspector>>
* <<extension-devutils-statelesschecker>>
* <<extension-wicketsource>>

=== General

[source,properties]
----
wicket.configurationType=development # development/deployment(default)

----

=== General - debugsettings

[source,properties]
----
wicket.core.debugsettings.enabled=true
wicket.core.debugsettings.developmentUtilitiesEnabled=true
wicket.core.debugsettings.ajaxDebugModeEnabled=false
wicket.core.debugsettings.componentUseCheck=false
wicket.core.debugsettings.outputMarkupContainerClassName=false
wicket.core.debugsettings.componentPathAttributeName=
----

[[extension-beanvalidation]]
=== Bean validation

[source,properties]
----
wicket.beanvalidation.enabled=true
----

[source,xml]
----
<dependency>
  <groupId>org.apache.wicket</groupId>
  <artifactId>wicket-bean-validation</artifactId>
</dependency>
----

[[extension-core-csrf-prevention]]
=== Core - Prevention of CSRF Attacks

[source,properties]
----
wicket.core.csrf.enabled=true
----

[[extension-webjars]]
=== Webjars

[source,xml]
----
<dependency>
  <groupId>de.agilecoders.wicket.webjars</groupId>
  <artifactId>wicket-webjars</artifactId>
</dependency>
----

[source,properties]
----
wicket.webjars.enabled=true
----

[[extension-wicketstuff-annotationscan]]
=== Wicketstuff - annotationscan

[source,xml]
----
<dependency>
  <groupId>org.wicketstuff</groupId>
  <artifactId>wicketstuff-annotation</artifactId>
</dependency>
----

[source,properties]
----
wicket.wicketstuff.annotationscan.enabled=true
wicket.wicketstuff.annotationscan.packagename=
----

[[extension-wicketstuff-htmlcompressor]]
=== Wicketstuff - htmlcompressor

[source,xml]
----
<dependency>
  <groupId>org.wicketstuff</groupId>
  <artifactId>wicketstuff-htmlcompressor</artifactId>
</dependency>
<dependency>
  <groupId>com.yahoo.platform.yui</groupId>
  <artifactId>yuicompressor</artifactId>
</dependency>
----

[source,properties]
----
wicket.wicketstuff.htmlcompressor.enabled=true
wicket.wicketstuff.htmlcompressor.features.*=
----

[[extension-wicketstuff-serializer-fast2]]
=== Wicketstuff - serializer-fast2

[source,xml]
----
<dependency>
  <groupId>org.wicketstuff</groupId>
  <artifactId>wicketstuff-serializer-fast2</artifactId>
</dependency>
----

[source,properties]
----
wicket.wicketstuff.serializer.fast2.enabled=true
----

[[extension-wicketstuff-serializer-kryo2]]
=== Wicketstuff - serializer-kryo2

[source,xml]
----
<dependency>
  <groupId>org.wicketstuff</groupId>
  <artifactId>wicketstuff-serializer-kryo2</artifactId>
</dependency>
----

[source,properties]
----
wicket.wicketstuff.serializer.fast2.enabled=true
----




[[extension-devutils]]
=== Devutils

[source,xml]
----
<dependency>
  <groupId>org.apache.wicket</groupId>
  <artifactId>wicket-devutils</artifactId>
</dependency>
----

[[extension-devutils-diskstorebrowser]]
==== Devutils - diskstorebrowser

[source,properties]
----
wicket.devutils.diskstorebrowser.enabled=false
wicket.devutils.diskstorebrowser.mountPage=devutils/diskstore/browser
----

[[extension-devutils-inspector]]
==== Devutils - inspector

[source,properties]
----
wicket.devutils.diskstorebrowser.enabled=false
wicket.devutils.diskstorebrowser.mountPage=devutils/diskstore/browser
----

[[extension-devutils-statelesschecker]]
==== Devutils - statelesschecker

[source,properties]
----
wicket.devutils.interceptor.enableLiveSessionsPage=false
wicket.devutils.interceptor.liveSessionPageMount=devutils/inspector/live-session-page
----

[[extension-wicketsource]]
=== Wicket-Source

[source,xml]
----
<dependency>
  <groupId>net.ftlines.wicket-source</groupId>
  <artifactId>wicket-source</artifactId>
</dependency>
----

[source,properties]
----
wicket.wicketsource.enabled=false
----


