= Wicket autoconfiguration with Spring Boot

NOTE: http://search.maven.org/#search|ga|1|com.giffing.wicket.spring.boot

This project (should) makes it easy to create Wicket projects with a minimum
of configuration effort. Is uses Spring Boot to autoconfigure Wickets core and
its extension with an reasonable default value which can be overridden over property files.

The detailed description of the autoconfiguration support can be read in the <<extension>> section.

Out of the box Wickets dependency injection support (@SpringBean) for Spring is automatically supported.
[source,java]
----
getComponentInstantiationListeners().add(new SpringComponentInjector(this, applicationContext));
---- 

Also Spring Security is automatically configured. You get a default login page and a default home page.
These pages can be overridden as usual like in any WicketApplication.
[source,java]
----
getSecuritySettings().setAuthorizationStrategy(new AnnotationsRoleAuthorizationStrategy(this));
----

:toc: macro

== Getting started

To get started you have to create a new Maven Project (or another preferred dependency/build-management tool)
and add the *wicket-spring-boot-starter* dependency to your configuration. 

[source,xml]
----
<dependency>
	<groupId>com.giffing.wicket.spring.boot.starter</groupId>
	<artifactId>wicket-spring-boot-starter</artifactId>
</dependency>
----

Beside the Maven dependency configuration we need the following steps to do

. Create a class (e.g. WicketApplication) with a main method
. Annotate the class with @WicketSpringBootApplication
. Extend this class with WicketBootWebApplication
. Use the SpringApplicationBuilder to run the WicketApplication class you've created


[source,java]
----
@WicketSpringBootApplication
public class WicketApplication extends WicketBootWebApplication {
  public static void main(String[] args) throws Exception {
    new SpringApplicationBuilder()
      .sources(WicketApplication.class)
      .run(args);
  }
}
----

Thats all! When you execute the main method you will get a fully working and configured 
Wicket application with a simple login and home Page. An embedded Tomcat is automatically started.
As in every Wicket application you can override the WicketBootWebApplication as usual. 
You can change the login/home page or the *init()* method to register other extensions. 

[[how_does_it_work]]
== How does it work?

To fully understand how http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-developing-auto-configuration[Spring Boots autconfiguration] 
and in general Spring Boot works you should read the excellent 
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/[documentation] from this fantastic http://projects.spring.io/spring-boot/[project].

As an an example we will look to the AnnotatedMountScanner configuration. The https://github.com/wicketstuff/core/wiki/Annotation[annotated mount scanner] 
is an project which supports bookmarkable URLs configured by annotations on WebPage classes. If you have this '@MountPath("login")' annotation on a 
WebPage then the Page is mounted to 'http://localhost/login'.

In this project each configuration is separated in two classes to configure this particular feature/extension. The extension
consists of a property and a configuration class.

The property class holds properties to configure the specific feature. In the AnnotatedMountScannerProperties class we
found two properties:

[source,java]
----
@ConfigurationProperties(prefix = AnnotatedMountScannerProperties.PROPERTY_PREFIX)
public class AnnotatedMountScannerProperties {
	public static final String PROPERTY_PREFIX = "wicket.wicketstuff.annotationscan";
	/**
	 * @see AnnotatedMountScannerConfig
	 */
	private boolean enabled = true;

	/**
	 * An alternative package name for scanning for mount path if the
	 * WicketApplication should not used as the root scan package
	 */
	private String packagename;
----

This property file can be imported in the configuration class AnnotatedMountScannerConfig.

[source,java]
----
/**
 * Auto configuration for the {@link AnnotatedMountScanner}.
 * 
 * It uses the user defined {@link WebApplication} as the default package scan
 * root directory.
 * 
 * Enables annotate mount scanner if the following two condition matches:
 * 
 * 1. The {@link AnnotatedMountScanner} is in the classpath.
 * 
 * 2. The property {@link AnnotatedMountScannerProperties#PROPERTY_PREFIX}
 * .enabled is true (default = true)
 * 
 * 
 * @author Marc Giffing
 *
 */
@ApplicationInitExtension
@ConditionalOnProperty(prefix = AnnotatedMountScannerProperties.PROPERTY_PREFIX, value = "enabled", matchIfMissing = true)
@ConditionalOnClass(value = org.wicketstuff.annotation.scan.AnnotatedMountScanner.class)
@EnableConfigurationProperties({ AnnotatedMountScannerProperties.class })
public class AnnotatedMountScannerConfig implements WicketApplicationInitConfiguration {

	@Autowired
	private AnnotatedMountScannerProperties prop;

	@Override
	public void init(WebApplication webApplication) {
		String packagename = webApplication.getClass().getPackage().getName();
		if (prop.getPackagename() != null) {
			packagename = prop.getPackagename();
		}
		new AnnotatedMountScanner().scanPackage(packagename).mount(webApplication);
	}
}
----

If all conditions on the AnnotatedMountScannerConfig matches the configuration class is configured as
a spring bean. All Spring beans which implements the interface WicketApplicationInitConfiguration will
be injected as a list in the default WicketBootWebApplication class.  

In the WicketBootWebApplication class we iterate in Wickets init method over the list and call on each the
init method to configure the application.

[source,java]
----
public class WicketBootWebApplication extends AuthenticatedWebApplication {
  @Autowired(required = false)
  private List<WicketApplicationInitConfiguration> configurations = new ArrayList<>();
  @Override
  protected void init() {
    super.init();
    for (WicketApplicationInitConfiguration configuration : configurations) {
      configuration.init(this);
    }
  }
}
----

=== Spring profile configuration

The Wicket Spring Boot Starter project ships with a default development configuration.
It can be activated by activating the 'development' Spring profile in the main class or over
external JVM/Maven arguments.

The default configuration can be overridden with a custom property file. See Spring Boots reference documentation http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config[here].

include::wicket-spring-boot-starter/src/main/resources/application-development.yml[]
[source,yml]
----
wicket:
  configuration-type: development
  core:
    debugsettings:
      enabled: true
  wicketstuff:
    htmlcompressor:
      enabled: false
      features:
        removeComments: false
        removeMultiSpaces: false
        removeIntertagSpaces: false
        removeQuotes: false
        compressJavaScript: false
        compressCss: false
        simpleDoctype: false
        removeScriptAttributes: false
        removeStyleAttributes: false
        removeLinkAttributes: false
        removeFormAttributes: false
        removeInputAttributes: false
        simpleBooleanAttributes: false
        removeJavaScriptProtocol: false
        removeHttpProtocol: false
        removeHttpsProtocol: false
        preserveLineBreaks: false
  devutils:
    statelesschecker:
      enabled: true
    interceptor:
      enable-live-sessions-page: true
    diskstorebrowser:
      enabled: true
  wicketsource:
    enabled: true
----

[[custom-conditions]]
== Custom conditions

This section lists custom conditional configuration like Spring Boot ones. 

=== @ConditionalOnWicket

With the ConditionOnWicket annotation you can check that configuration classes only apply
on a specific Wicket major version. If some functionality is only available on Wicket 7 
you can use this annotation.

[source,java]
----
@ApplicationInitExtension
@ConditionalOnWicket(value=7, range=Range.EQUALS_OR_HIGHER)
public ConditionalConfig implements WicketApplicationInitConfiguration{
	@Override
	public void init(WebApplication webApplication) {
		// configuration option which only apply to Wickets major version 7 or higher
	}
}
----

[[extension]]
== Extensions

The following section describes the current extensions and there
required dependencies. An extension is a custom labeling in this project
which is used to auto-configure a specific part of an Wicket application. An extension
may require an external dependency or is using core features. See section
<<how_does_it_work>> to get a deeper knowledge.

* <<extension-general>>
** DEPLOYMENT-CONFIGURATIONS
*** <<extension-beanvalidation>>
*** <<extension-core-csrf-prevention>>
*** <<extension-webjars>>
*** <<extension-wicketstuff-htmlcompressor>>
*** <<extension-wicketstuff-annotationscan>>
*** <<extension-core-serializer-deflated>>
*** <<extension-wicketstuff-serializer-fast2>>
*** <<extension-wicketstuff-serializer-kryo2>>
*** <<extension-datastore-cassandra>>
*** <<extension-datastore-hazelcast>>
*** <<extension-datastore-memcached>>
*** <<extension-datastore-redis>>

** DEVELOPMENT-CONFIGURATIONS
*** <<extension-general-debugsettings>>
*** <<extension-devutils-diskstorebrowser>>
*** <<extension-devutils-inspector>>
*** <<extension-devutils-statelesschecker>>
*** <<extension-wicketsource>>

[[extension-general]]
=== General

Wicket can be started in DEVELOPMENT and DEPLOYMENT mode. You can change the
configuration type over the following property configuration. The given property
is automatically mapped to Wickets ConfigurationType enumeration. 
 

[source,properties]
----
wicket.configuration-type=development # development/deployment(default)
wicket.render-strategy=redirect-to-buffer # redirect-to-buffer / one-pass-render / redirect-to-render
----
If you insert e.g. developmentx you will get a startup error:
[listing]
Field error in object 'wicket' on field 'configurationType': rejected value [developmentx]; codes [typeMismatch.wicket.configurationType

[[extension-beanvalidation]]
=== Bean validation

Wicket support for JSR 303 Bean validation.
See Wickets user guide 
https://ci.apache.org/projects/wicket/guide/7.x/guide/single.html[Validation with JSR 303]

To enable Wickets bean validation you have to add the *wicket-bean-validation* dependency to your
project. It will automatically configured and can be used in the project.

[source,properties]
----
wicket.beanvalidation.enabled=true # enabled by default if bean validation project is present
----

[source,xml]
----
<dependency>
  <groupId>org.apache.wicket</groupId>
  <artifactId>wicket-bean-validation</artifactId>
</dependency>
----

[[extension-core-csrf-prevention]]
=== Core - Prevention of CSRF Attacks



[source,properties]
----
wicket.core.csrf.enabled=true
#TODO: There are some configuration options which should be added
----

[[extension-webjars]]
=== Webjars

https://github.com/l0rdn1kk0n/wicket-webjars

[source,properties]
----
wicket.webjars.enabled=true
----

[source,xml]
----
<dependency>
  <groupId>de.agilecoders.wicket.webjars</groupId>
  <artifactId>wicket-webjars</artifactId>
</dependency>
----

[[extension-wicketstuff-annotationscan]]
=== Wicketstuff - annotationscan

Use wicketstuff-annotation to use Java Annotations and class path searching to mount your Wicket pages.

See https://github.com/wicketstuff/core/wiki/Annotation[documentation]

[source,xml]
----
<dependency>
  <groupId>org.wicketstuff</groupId>
  <artifactId>wicketstuff-annotation</artifactId>
</dependency>
----

[source,properties]
----
wicket.wicketstuff.annotationscan.enabled=true
wicket.wicketstuff.annotationscan.packagename=
----

[[extension-wicketstuff-htmlcompressor]]
=== Wicketstuff - htmlcompressor

See https://github.com/wicketstuff/core/wiki/Htmlcompressor[documentation]

[source,xml]
----
<dependency>
  <groupId>org.wicketstuff</groupId>
  <artifactId>wicketstuff-htmlcompressor</artifactId>
</dependency>
<dependency>
  <groupId>com.yahoo.platform.yui</groupId>
  <artifactId>yuicompressor</artifactId>
</dependency>
----

[source,properties]
----
wicket.wicketstuff.htmlcompressor.enabled=true
wicket.wicketstuff.htmlcompressor.features.*=
----

[[extension-core-serializer-deflated]]
=== Core - serializer-deflated

[source,properties]
----
wicket.core.serializer.deflated.enabled=false # has to be explicit enabled. deflates the outputstream, reducing page store size by up to a factor 8 at a price of about 2-20ms
----

[[extension-wicketstuff-serializer-fast2]]
=== Wicketstuff - serializer-fast2

See https://github.com/wicketstuff/core/wiki/FastSerializer2[documentation]

[source,xml]
----
<dependency>
  <groupId>org.wicketstuff</groupId>
  <artifactId>wicketstuff-serializer-fast2</artifactId>
</dependency>
----


[source,properties]
----
wicket.wicketstuff.serializer.fast2.enabled=true
----

[[extension-wicketstuff-serializer-kryo2]]
=== Wicketstuff - serializer-kryo2

See https://github.com/wicketstuff/core/wiki/Kryo-Serializer[documentation]

[source,xml]
----
<dependency>
  <groupId>org.wicketstuff</groupId>
  <artifactId>wicketstuff-serializer-kryo2</artifactId>
</dependency>
----

[source,properties]
----
wicket.wicketstuff.serializer.fast2.enabled=true
----

[[extension-general-debugsettings]]
=== General - debugsettings

Wicket provides some debug settings which could be 

[source,properties]
----
wicket.core.debugsettings.enabled=true
wicket.core.debugsettings.developmentUtilitiesEnabled=true # Enables all of the panels and pages, etc, from wicket-devutils package.
wicket.core.debugsettings.ajaxDebugModeEnabled=false # if true: wicket-ajax-debug.js is added to header
wicket.core.debugsettings.componentUseCheck=true
wicket.core.debugsettings.outputMarkupContainerClassName=false
wicket.core.debugsettings.componentPathAttributeName=
----

[[extension-datastore]]
== Datastore

See https://github.com/wicketstuff/core/wiki/DataStores[Documentation]

[[extension-datastore-cassandra]]
=== Datastore cassandra

[source,properties]
----
wicket.datastore.cassandra.enabled=true
wicket.datastore.cassandra.contact-points= #comma-separated list 
wicket.datastore.cassandra.table-name=pagestore
wicket.datastore.cassandra.keyspace-name=wicket
wicket.datastore.cassandra.record-ttl=30
wicket.datastore.cassandra.record-ttl-unit=minutes
wicket.datastore.cassandra.session-size=2
wicket.datastore.cassandra.session-unit=megabytes
----

[source,xml]
----
<dependency>
  <groupId>org.wicketstuff</groupId>
  <artifactId>wicketstuff-datastore-cassandra</artifactId>
</dependency>
----

[[extension-datastore-hazelcast]]
=== Datastore hazelcast

[source,properties]
----
wicket.datastore.hazelcast.enabled=true
wicket.datastore.hazelcast.session-size=2L 
wicket.datastore.hazelcast.session-unit=megabytes
----

[source,xml]
----
<dependency>
  <groupId>org.wicketstuff</groupId>
  <artifactId>wicketstuff-datastore-hazelcast</artifactId>
</dependency>
<dependency>
  <groupId>com.hazelcast</groupId>
  <artifactId>hazelcast</artifactId>
</dependency>
----

[[extension-datastore-memcached]]
=== Datastore memcached

[source,properties]
----
wicket.datastore.memcached.enabled=true
wicket.datastore.memcached.session-size=2L 
wicket.datastore.memcached.session-unit=megabytes
wicket.datastore.memcached.expiration-time=30
wicket.datastore.memcached.port=11211
wicket.datastore.memcached.server-names=
wicket.datastore.memcached.shutdown-timeout=30
wicket.datastore.memcached.shutdown-timeout-unit=minutes
----

[source,xml]
----
<dependency>
  <groupId>org.wicketstuff</groupId>
  <artifactId>wicketstuff-datastore-memcached</artifactId>
</dependency>
----

[[extension-datastore-redis]]
=== Datastore redis

[source,properties]
----
wicket.datastore.redis.enabled=true
wicket.datastore.redis.session-size=2L 
wicket.datastore.redis.session-unit=megabytes
wicket.datastore.redis.expiration-time=30
wicket.datastore.redis.port=11211
wicket.datastore.redis.server-names=
wicket.datastore.redis.shutdown-timeout=30
wicket.datastore.redis.shutdown-timeout-unit=minutes
----

[source,xml]
----
<dependency>
  <groupId>org.wicketstuff</groupId>
  <artifactId>wicketstuff-datastore-redis</artifactId>
</dependency>
----


[[extension-devutils]]
=== Devutils

[source,xml]
----
<dependency>
  <groupId>org.apache.wicket</groupId>
  <artifactId>wicket-devutils</artifactId>
</dependency>
----

[[extension-devutils-diskstorebrowser]]
==== Devutils - diskstorebrowser

[source,properties]
----
wicket.devutils.diskstorebrowser.enabled=false
wicket.devutils.diskstorebrowser.mountPage=devutils/diskstore/browser
----

[[extension-devutils-inspector]]
==== Devutils - inspector

[source,properties]
----
wicket.devutils.diskstorebrowser.enabled=false
wicket.devutils.diskstorebrowser.mountPage=devutils/diskstore/browser
----

[[extension-devutils-statelesschecker]]
==== Devutils - statelesschecker

[source,properties]
----
wicket.devutils.interceptor.enableLiveSessionsPage=false
wicket.devutils.interceptor.liveSessionPageMount=devutils/inspector/live-session-page
----

[[extension-wicketsource]]
=== Wicket-Source

See https://github.com/42Lines/wicket-source/wiki[documentation]

[source,xml]
----
<dependency>
  <groupId>net.ftlines.wicket-source</groupId>
  <artifactId>wicket-source</artifactId>
</dependency>
----

[source,properties]
----
wicket.wicketsource.enabled=false
----


